### ISSUE TITLE
Almost Passing

### ISSUE THREAD

**Issue by natepill** [UPstartDeveloper/Superhero-Team-Dueler#1]
**Errors thrown are preventing me from evaluating the rest of the project **
**Below is my terminal input/output for where I'm getting my error thrown:**

Enter name for Team One: adsasd
Enter the size of this team: 1
----------------------------------------
Is this Hero able to steal(Y/N)? Y
Enter a name for your new hero: asdasd
Would you like to add a new ability (Y/N)?Y
----------------------------------------
Enter the name for your new ability: asdasd
Enter attack power.
All attacks below 9000 are authorized: 222
Traceback (most recent call last):
  File "superheroes.py", line 641, in <module>
    arena.build_team_one()
  File "superheroes.py", line 500, in build_team_one
    new_team_player = self.create_hero()
  File "superheroes.py", line 478, in create_hero
    self.prompt_all(new_hero)
  File "superheroes.py", line 463, in prompt_all
    self.prompt_for(hero, "ability")
  File "superheroes.py", line 449, in prompt_for
    new_ability = self.create_powers("ability")
  File "superheroes.py", line 430, in create_powers
    return Ability(name, strength, authorized)
TypeError: __init__() takes 3 positional arguments but 4 were given

**Comment by UPstartDeveloper** [comment]
My bad, I totally missed that the authorized parameter was no longer used in the Ability class init method. I changed the error, should be fixed now.
